#setwd("C:/Users/aman/Desktop/DataRProject1")
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
#library(rgdal)
#library(leaflet)
library(googleVis)

co2 = read.csv("./input/co2 _emission.csv", stringsAsFactors = F)
co2$CO2.Emissions = as.numeric( gsub( ",", "", co2$CO2.Emissions) )
co2$Emissions.from.bunker.fuels = as.numeric( gsub( ",", "", co2$Emissions.from.bunker.fuels ))
co2$Emissions.from.gas.flaring = as.numeric( gsub( ",", "", co2$Emissions.from.gas.flaring))
co2$Emissions.from.cement.production = as.numeric( gsub( ",", "", co2$Emissions.from.cement.production))
co2$Emissions.from.gas.fuel.consumption = as.numeric( gsub( ",", "", co2$Emissions.from.gas.fuel.consumption))
co2$Emissions.from.solid.fuel.consumption = as.numeric(gsub( ",", "", co2$Emissions.from.solid.fuel.consumption))
co2$Emissions.from.liquid.fuel.consumption  = as.numeric((gsub( ",", "", co2$Emissions.from.liquid.fuel.consumption)))
co2$Gdp.Ppp = as.numeric(gsub( ",", "", co2$Gdp.Ppp))